package com.example.laserrailwaydrapp
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@Composable
fun QRGeneratorScreen(user: User?) {
    var data by remember { mutableStateOf("") }
    var qrCodeGenerated by remember { mutableStateOf(false) }

    Column(
        Modifier
            .fillMaxSize()
            .padding(16.dp),
        verticalArrangement = Arrangement.Center
    ) {
        Text("QR Code Generator", style = MaterialTheme.typography.headlineMedium)
        Spacer(modifier = Modifier.height(16.dp))

        OutlinedTextField(
            value = data,
            onValueChange = { data = it },
            label = { Text("Enter Data") },
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(16.dp))
        Button(onClick = { qrCodeGenerated = true }, modifier = Modifier.fillMaxWidth()) {
            Text("Generate QR Code")
        }

        if (qrCodeGenerated) {
            Spacer(modifier = Modifier.height(16.dp))
            Text("QR Code generated for: $data")
            // TODO: Integrate actual QR code generation library later
        }


    }
}
